name: Build And Test

on:
  push:
    branches: [ "develop", "main", "refactor" ]
  pull_request:
    branches: [ "develop", "main", "refactor" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MARIADB_ROOT_PASSWORD: '<password>'
          MARIADB_DATABASE: 'harmonize_test'
          MARIADB_USER: test_user
          MARIADB_PASSWORD: test_password
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build -x test

      - name: Test with Gradle
        env:
          SMTP_HOST: smtp.example.com
          SMTP_PORT: '587'
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: SPRING_PROFILES_ACTIVE=[test] ./gradlew test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.6.1
        if: ${{ always() }}  # 테스트가 실패하여도 Report를 보기 위해 `always`로 설정
        with:
          files: build/test-results/**/*.xml